---
name: Build and Push Mutalyzer

on:
  push:
    tags:
      - 'v*.*.*'
    branches: ["pla-319-mutalyzer-deploy"]

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::128661210372:role/github-actions/github-ecr
          aws-region: eu-west-2
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr
      - uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64
      - name: get short git_sha
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        id: git_sha
      - name: Build and Push Mutalyzer
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/mutalyzer:${{ github.ref_name }} , ${{ steps.login-ecr.outputs.registry }}/mutalyzer:sha-${{ steps.git_sha.outputs.short_sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
